InterPayIR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from interpay import views
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView
# from two_factor.urls import urlpatterns as tf_urls
# from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls
from django_twilio.views import message

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'session_security/', include('session_security.urls')),
    # url(r'', include('two_factor.urls', 'two_factor')),
    # url(r'^accounts/', include('registration.backends.hmac.urls')),
    # url(r'', include(tf_urls + tf_twilio_urls, 'two_factor')),
    url(r'^message/$', message, {
        'message': 'Thanks for the SMS. Talk to you soon!',
    }),

    # url(r'^$', TemplateView.as_view(template_name="main_page.html")),
    # url(r'^home/', TemplateView.as_view(template_name="home.html")),
    # url(r'^wallets/', TemplateView.as_view(template_name="wallets.html")),
    # url(r'^trans-history/', TemplateView.as_view(template_name="trans_history.html")),
    # url(r'^reports/', TemplateView.as_view(template_name="reports.html"), name='reports'),
    # url(r'^general/', TemplateView.as_view(template_name="home.html"), name='general'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^$', views.main_page),
    url(r'^home/', views.home),
    url(r'^wallets/', views.wallets),
    url(r'^trans-history/', views.trans_history),
    url(r'^reports/', views.reports, name='reports'),
    url(r'^general/', views.general, name='general'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^sms/$', views.send_sms, name='sms'),

]

urlpatterns += i18n_patterns(
    # url(r'^accounts/', include('registration.backends.hmac.urls')),

    # url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name="main_page.html")),
    # url(r'^home/', TemplateView.as_view(template_name="home.html")),
    # url(r'^wallets/', TemplateView.as_view(template_name="wallets.html")),
    # url(r'^trans-history/', TemplateView.as_view(template_name="trans_history.html")),
    # url(r'^reports/', TemplateView.as_view(template_name="reports.html"), name='reports'),
    # url(r'^general/', TemplateView.as_view(template_name="home.html"), name='general'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url(r'session_security/', include('session_security.urls')),
    # url(r'', include('two_factor.urls', 'two_factor')),
    # url(r'', include(tf_urls + tf_twilio_urls, 'two_factor')),
    # url(r'^message/$', message, {
    #     'message': 'Thanks for the SMS. Talk to you soon!',
    # }),

    url(r'^$', views.main_page),
    url(r'^home/', views.home),
    url(r'^wallets/', views.wallets),
    url(r'^trans-history/', views.trans_history),
    url(r'^reports/', views.reports, name='reports'),
    url(r'^general/', views.general, name='general'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^sms/$', views.send_sms, name='sms'),
)

interpay/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.core.mail import send_mail
from django.core.validators import RegexValidator, int_list_validator
from django.utils.encoding import force_text
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from django.forms import ChoiceField
from django_countries.fields import CountryField
from datetime import datetime
import unicodedata


class Manager(BaseUserManager):
    def create_user(self, USERNAME_FIELD, email, password):
        email = self.normalize_email(email)
        username = self.model.normalize_username(USERNAME_FIELD)
        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="UserProfile")
    password = models.CharField(max_length=10, null=False, blank=False)
    picture = models.ImageField(upload_to='userProfiles/', null=True, blank=True)
    date_of_birth = models.DateTimeField(null=False, blank=False)
    date_joined = models.DateTimeField(default=datetime.now())
    country = CountryField(default="Iran")
    national_code = models.CharField(max_length=10, null=False, blank=False)
    mobile_number = models.CharField(max_length=11, null=True, blank=True)
    email = models.EmailField(null=False, blank=False)
    # TODO : this field should not be nullable. fix it.
    national_card_photo = models.ImageField(upload_to='nationalCardScans/', null=True, blank=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    objects = Manager()

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return '{}'.format(self.user.username)

    def __unicode__(self):
        return self.user.username

        # def __init__(self, *args, **kwargs):
        #     super(UserProfile, self).__init__(*args, **kwargs)
        #     if self.instance:
        #         # we're operating on an existing object, not a new one...
        #         country = self.instance.country
        #         cities = self.fields["new_city"] = ChoiceField(choices=cities)


class CommonUser(models.Model):
    # since we might need to define a Manager model in the future, this model is named as "CommonUser"
    user_ID = models.ForeignKey(UserProfile, null=False, related_name='user_ID')

    def __str__(self):
        return '{} - {}'.format(self.customer_ID, self.user_ID.name)

interpay/views.py
from dircache import cache
import random
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, redirect
from django.views import View
from django.views.generic import TemplateView, CreateView
from twilio.rest import TwilioRestClient
from interpay.forms import RegistrationForm, UserForm
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from interpay.models import UserProfile
from django.utils import translation
from InterPayIR import settings


def main_page(request):
    if request.user.is_authenticated():
        return home(request)
    return render(request, 'index.html')


# class RegistrationView(CreateView):
#     template_name = '../templates/registeration_form.html'
#     user_form = UserForm
#     registration_form = RegistrationForm
#     model = UserProfile
#     registered = False
#
#     def post(self, request, *args, **kwargs):
#         print("post called")
#         user_form = UserForm(data=request.POST)
#         registration_form = RegistrationForm(data=request.POST)
#         return self.my_form_valid(user_form)
#
#     def my_form_valid(self, user_form, request):
#         print("is valid called")
#         user = user_form.save()
#         user.set_password(user.password)
#         user.save()
#
#         user_profile = self.registration_form.save(commit=False)
#         user_profile.email = user_form.cleaned_data['email']
#         user_profile.password = user.password
#
#         if user.is_active:
#             user_profile.is_active = True
#         user_profile.user = user
#
#         if 'picture' in request.FILES:
#             user_profile.picture = request.FILES['picture']
#         user_profile.save()
#         self.registered = True
#
#         new_user = authenticate(username=user_form.cleaned_data['username'],
#                                 password=user_form.cleaned_data['password'], )
#         login(request, new_user)
#
#     def get(self):
#         user_form = UserForm()
#         registration_form = RegistrationForm()


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        registration_form = RegistrationForm(data=request.POST)

        if user_form.is_valid() and registration_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_profile = registration_form.save(commit=False)
            user_profile.email = user_form.cleaned_data['email']
            # user_profile.date_of_birth = user_profile.cleaned_data['date_of_birth']
            user_profile.password = user.password
            # print(user.is_active, "ine")
            if user.is_active:
                user_profile.is_active = True
            user_profile.user = user

            if 'picture' in request.FILES:
                user_profile.picture = request.FILES['picture']
            if 'national_card_photo' in request.FILES:
                user_profile.national_card_photo = request.FILES['national_card_photo']
            user_profile.save()
            registered = True

            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password'], )
            login(request, new_user)

        else:
            print user_form.errors, registration_form.errors

    else:
        user_form = UserForm()
        registration_form = RegistrationForm()
    # print(request.LANGUAGE_CODE, " reg")
    if request.LANGUAGE_CODE == 'en-gb':
        # print(request.LANGUAGE_CODE, " register")
        thanks_msg = "Thank You for Registering!"
        redirect_to_home_msg = 'Launch to your homepage'
        # dict = {thanks_msg, redirect_to_home_msg}
        return render(request, 'registeration_form.html',
                      {'user_form': user_form, 'profile_form': registration_form, 'registered': registered,
                       'thanks_msg': thanks_msg, 'redirect_to_home_msg': redirect_to_home_msg})
    else:
        thanks_msg = "???? ?????? ??? ?? ?????? ????? ??."
        redirect_to_home_msg = '???? ???? ??? ?? ??????.'
        # dict = {thanks_msg, redirect_to_home_msg}
        return render(request, 'registeration_form.html',
                      {'user_form': user_form, 'profile_form': registration_form, 'registered': registered,
                       'thanks_msg': thanks_msg, 'redirect_to_home_msg': redirect_to_home_msg})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user, None)
                if request.LANGUAGE_CODE == 'en-gb':
                    return HttpResponseRedirect('/home/')
                else:
                    return HttpResponseRedirect('/fa-ir' + request.path)
            else:
                if request.LANGUAGE_CODE == 'en-gb':
                    en_acc_disabled_msg = "Your account is disabled."
                    return render(request, 'index.html', {'msg': en_acc_disabled_msg})
                else:
                    fa_acc_disabled_msg = u'???? ?????? ??? ????? ??? ???.'
                    return render(request, 'index.html', {'msg': fa_acc_disabled_msg})
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            if request.LANGUAGE_CODE == 'en-gb':
                en_wrong_info_msg = "Username or Password is not valid. please try again."
                return render(request, 'index.html', {'msg': en_wrong_info_msg})
            else:
                fa_wrong_info_msg = u'??? ?????? ?? ??? ???? ???? ??? ?????? ???.'
                return render(request, 'index.html', {'msg': fa_wrong_info_msg})
    else:
        return render(request, 'index.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required()
def home(request):
    return render(request, "home.html")


class HomeView(TemplateView):
    template_name = 'home.html'


@login_required()
def wallets(request):
    return render(request, "wallets.html")


@login_required()
def trans_history(request):
    return render(request, "trans_history.html")


@login_required()
def reports(request):
    return render(request, "reports.html")


@login_required()
def general(request):
    return render(request, "general.html")


# def _get_pin(length=5):
#     """ Return a numeric PIN with length digits """
#     return random.sample(range(10 ** (length - 1), 10 ** length), 1)[0]
#
#
# def _verify_pin(mobile_number, pin):
#     """ Verify a PIN is correct """
#     return pin == cache.get(mobile_number)
#
#
# def ajax_send_pin(request):
#     """ Sends SMS PIN to the specified number """
#     mobile_number = request.POST.get('mobile_number', "")
#     if not mobile_number:
#         return HttpResponse("No mobile number", mimetype='text/plain', status=403)
#
#     pin = _get_pin()
#
#     # store the PIN in the cache for later verification.
#     cache.set(mobile_number, pin, 24 * 3600)  # valid for 24 hrs
#
#     client = TwilioRestClient(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
#     message = client.messages.create(
#         body="%s" % pin,
#         to=mobile_number,
#         from_=settings.TWILIO_FROM_NUMBER,
#     )
#     return HttpResponse("Message %s sent" % message.sid, mimetype='text/plain', status=200)

# from InterPayIR.SMS import api
# def send_sms(request):
#     p = api.ParsGreenSmsServiceClient()
#     return api.ParsGreenSmsServiceClient.sendSms(p)

interpay/templates/general.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        <h3 class="page-title">{% block title %}{% trans 'General' %}{% endblock %}</h3>
    </title>
</head>
<body>
{% block cont-header %}
    <div>
        <h3 class="page-title">
            {% trans 'General' %}
        </h3>
    </div>
{% endblock %}
{% block cont-body %}
    {% trans 'This page is still under construction ... . we will be at your service soon.' %}
{% endblock %}
</body>
</html>

interpay/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="../static/jquery/jquery-1.10.2.min.js"></script>
    {% block CSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    {% endblock %}
    <meta charset="UTF-8">
    <title>{% block title %}
        Home Page
    {% endblock %}</title>
</head>
<body>
{% block cont-header %}
    <div id="welcome-msg" >

        <h3 class="page-title"> {% trans "Welcome to interpay" %}</h3>
    </div>
{% endblock %}
{% block cont-body %}
    <div id="interpay-desc">
        <p>
            {% trans 'Interpay is an online electronic service which provides a safe and secure platform for business transactions and e-commerce. No matter you are the merchant or the consumer, we will bring you an enjoyable experience of transaction.' %}
        </p>
    </div>
{% endblock %}

</body>
</html>

interpay/templates/index.html
{% extends 'registeration_form.html' %}
{% load staticfiles %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>InterPay Iran</title>
    {% block CSS %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock %}

</head>
<body>
<script>
    function send_pin() {
        $.ajax({
            url: "{% url 'ajax_send_pin' %}",
            type: "POST",
            data: {mobile_number: $("#mobile_number").val()},
        })
                .done(function (data) {
                    alert("PIN sent via SMS!");
                })
                .fail(function (jqXHR, textStatus, errorThrown) {
                    alert(errorThrown + ' : ' + jqXHR.responseText);
                });
    }
</script>
<header>
    <div class="top-bar">
        <div class="container" style="color: white;">
            <b>{% block header_title %}
                Welcome to InterPay Iran (Rizpardakht)
            {% endblock %}</b>

            <div class="row">
                <div id="number" class="col-sm-6 col-xs-4"></div>
                <div id="social" class="col-sm-6 col-xs-8"></div>
            </div>
        </div>
    </div>
    <nav></nav>
</header>
<section>
    <div class="container">
        <div class="row">
            {% block main-cont %}

                <div class="col-xs-12" style="text-align: center ">
                    <h3 style="margin-top: 40px">{% trans 'Welcome to Interpay Iran' %}</h3>

                    <div class="form-wrapper" id="login-form-wrapper">
                        <div style="font-size: larger"><i class="fa fa-sign-in" style="padding-right: 5px"
                                                          aria-hidden="true"></i>
                            {% trans 'Login to Interpay' %}
                        </div>
                        <div>{% block message %}
                            {% if msg %}
                                {#                                TODO this style should be omitted and implemented via registration-form.css #}
                                <div class="form-msg"
                                     style="padding: 10px 5px;color: red;font-size: small;margin-top: 5px"><i
                                        class="fa fa-exclamation-triangle" style="color: red"
                                        aria-hidden="true"></i> {{ msg }}</div>
                            {% endif %}
                        {% endblock %}</div>
                        <hr>
                        <form id="login_form" method="post" action="/login/">
                            {% csrf_token %}
                            <div id="username-div"><input class="login-form-field" type="text" name="username"
                                                          id="username" value=""
                                                          placeholder="Username" size="50"/>
                            </div>
                            <div id="password-div"><input class="login-form-field" type="password" name="password"
                                                          id="password" value=""
                                                          placeholder="Password" size="50"/>
                            </div>
                            {#                            <input type="text" id="mobile_number" name="mobile_number" placeholder="111-111-1111"#}
                            {#                                   required>#}
                            {#                            <button class="btn" type="button" onClick="send_pin()"><i class="icon-share"></i> Get PIN#}
                            {#                            </button>#}
                            <div id="lgn-btn-div" style="text-align: center"><input
                                    id="submit-btn"
                                    class="btn btn-info" type="submit"
                                    value="{% trans 'Login' %}"/></div>
                        </form>
                    </div>
                    <div id="register-div">
                        <h6>{% trans "Don't have an account yet?" %}</h6>
                        {% ifequal LANGUAGE_CODE  'en-gb' %}
                            <a id="register-link" href="/register/">
                        {% else %}
                            <a id="register-link" href="/fa-ir/register/">
                        {% endifequal %}
                        {% trans 'Create One!' %}
                        </a><br/>

                        {#                        <a id="register-link" href="/register/">{% trans 'Create One!' %}</a>#}
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</section>

</body>
</html>

interpay/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>InterPay Iran</title>
    </head>

    <body>
        <h1>Login to InterPay</h1>

        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

    </body>
</html>

interpay/templates/registeration_form.html
{% load i18n %}
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        InterPay Iran
    </title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static "bower_components/font-awesome/css/font-awesome.css" %}">
    <link rel="stylesheet" href="{% static "bower_components/font-awesome/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static 'css/registeration_form.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/ipay-favicon.ico' %}"/>
    {% block CSS %}
    {% endblock %}


    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

    {% block JS %}
    {% endblock %}



    <style>
        {% ifequal LANGUAGE_CODE 'fa-ir' %}
            .form-wrapper {
                text-align: right !important;
            }

            #sidebar-entries {
                padding-right: 10px;
                padding-left: 0 !important;
            }

            .sidebar-entry {
                text-align: right;
                direction: rtl;
            }

            #logout {
                float: left !important;
            }

            #name {
                float: right !important;
            }

            #interpay-id {
                float: right !important;
            }
        {% endifequal %}
    </style>

    {% block style %}
    {% endblock %}
</head>

<body style="background: #f9f9f9">
<script>
    $(document).ready(function () {
        $("#national_code").keydown(function (event) {
            // Allow: backspace, delete, tab, escape, and enter
            if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 ||
                        // Allow: Ctrl+A
                    (event.keyCode == 65 && event.ctrlKey === true) ||
                        // Allow: home, end, left, right
                    (event.keyCode >= 35 && event.keyCode <= 39)) {
                // let it happen, don't do anything
            }
            else {
                // Ensure that it is a number and stop the keypress
                if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
                    event.preventDefault();
                }
            }
        });

        $("#mob_no").keydown(function (event) {
            // Allow: backspace, delete, tab, escape, and enter
            if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 ||
                        // Allow: Ctrl+A
                    (event.keyCode == 65 && event.ctrlKey === true) ||
                        // Allow: home, end, left, right
                    (event.keyCode >= 35 && event.keyCode <= 39)) {
                // let it happen, don't do anything
            }
            else {
                // Ensure that it is a number and stop the keypress
                if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
                    event.preventDefault();
                }
            }
        });
        {#        $(function () {#}
        {#            $("#id_date_of_birth").datepicker("show");#}
        {#            $("#format"id_date_of_birth").datepicker("option", "dateFormat", $(this).val());#}
        {#            });).change(function () {#}
        {#                $("##}
        {#        });#}
        {#        console.log("k");#}
        {#        $("#id_date_of_birth").click(function () {#}
        {#            console.log("hi");#}
        {#            $("#id_date_of_birth").datepicker("show");#}
        {#        });#}
    });

    function to_en() {
        var en_url = window.location.href.replace("/fa-ir/", "/");
        window.location.assign(en_url);
    }

    function id_card_submit_btn() {
        console.log("hey");
        $('#id_national_card_photo').click();
    }
</script>
<header>
    <div class="top-bar">
        <div class="container" style="color: white;">
            <div id="logo-bar">
                <img src="/static/images/logo.png" style="width: 10%">
                <!--The translation part is commented out until it's bug being fixed -->
                {#                <div id="translation-link">#}
                {#                    {% ifequal LANGUAGE_CODE  'en-gb' %}#}
                {#                        <a id="to-fa-link" href='/fa-ir{{ request.path }}'><img src="../static/images/irflag.png"#}
                {#                                                                                style="width: 50%;cursor: pointer"></a>#}
                {#                    {% else %}#}
                {#                        <a id="to-en-link" class="trans-link" onclick="to_en()"><img src="../static/images/ukflag.png"#}
                {#                                                                                     style="width: 50%;cursor: pointer"></a>#}
                {#                    {% endifequal %}#}
                {#                </div>#}
            </div>
            {#            <div class="row">#}
            {#                <div id="number" class="col-sm-6 col-xs-4"></div>#}
            {#                <div id="social" class="col-sm-6 col-xs-8"></div>#}
            {#            </div>#}

        </div>
    </div>
    <nav></nav>

</header>
<section>
    <div class="container">
        {% if registered %}
            <div class="row">
                <div class="col-xs-12" id="reg-wrap-wrap-div">
                    <div class="form-wrapper" style="text-align: center">
                        <strong>{{ thanks_msg }}</strong>
                        <hr>
                        {#                        <a class="btn-link" href="/home">{% trans 'Launch to your homepage' %}</a><br/>#}

                        {#                        {% ifequal LANGUAGE_CODE  'en-gb' %}#}
                        <a class="btn-link" href="/home/">{{ redirect_to_home_msg }}
                            {#                        {% else %}#}
                            {#                            <a class="btn-link" href="/fa-ir/home/">#}
                            {#                        {% endifequal %}#}
                            {#                        {% trans 'Launch to your homepage' %}#}
                        </a><br/>

                    </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                {% block main-cont %}
                    <div class="col-xs-12" id="reg-wrap-wrap-div">
                        <div class="form-wrapper">
                            <div></div>
                            <div id="reg-top-icon" style="margin: 5px;font-size: larger">
                                <i class="fa fa-users" aria-hidden="true"
                                   style="padding-right: 5px"></i>
                                {% trans 'New User Registration' %}
                            </div>
                            {% block message %}
                            {% endblock %}
                            <hr>
                            <form enctype="multipart/form-data" id="registration_form" method="post"
                                  action="/register/" > {% csrf_token %}
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                                <p>
                                    <input id="id-card-submit-btn" type="button"
                                           value="{% trans 'Upload your Identification Card photo' %}"
                                           class="registration-form-field btn btn-primary"
                                           onclick="id_card_submit_btn()">
                                </p>

                                <div id="submit-btn-wrap" style="text-align: center">
                                    <input id="submit-btn" class="btn btn-success" type="submit" name="submit"
                                           value="{% trans 'Sign Up' %}"/>
                                </div>
                            </form>
                            <a></a>

                            <div></div>
                            <div></div>
                        </div>
                        <div class="login-register-div">
                            <h6>{% trans 'Already have an account?' %}</h6>
                            <a class="register-login-link" href="/login/">{% trans 'Sign In!' %}</a>
                        </div>
                    </div>
                {% endblock %}
            </div>
        {% endif %}
    </div>
</section>
{#TODO this part should be fixed ASAP#}
{#<footer id="footer" class="footer">#}
{#    <div id="footer-content">All rights reserved.</div>#}
{#</footer>#}
</body>
</html>

interpay/templates/reports.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {% trans 'Reports' %}
        {% endblock %}
    </title>
    {% block CSS %}
        <link rel="stylesheet" href="{% static 'css/reports.css' %}">
    {% endblock %}
</head>
<body>
{% block cont-header %}
    <div>
        <h3 class="page-title">
            {% trans 'Wallet Report' %}
        </h3>
    </div>
{% endblock %}
{% block cont-body %}
    {% trans 'This page is still under construction ... . we will be at your service soon.' %}
{% endblock %}
</body>
</html>